spring:
  application:
    name: kookil-backend
  profiles:
    active: local  # ????? ?? ??? ?? (????? prod? ????)

  # ?? ?? ??? ??
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# ?? ??
server:
  port: 8080