spring:
  application:
    name: kookil-backend

  datasource:
    # MariaDB ?? ?? (?? ?? ??)
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kookil_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root          # ?? DB ??? (?? root)
    password: 1234          # ?? DB ???? ?? ??!

  jpa:
    # ?? ? DB ??? ?? ?? (create: ?? ??? ???, update: ???? ??, none: ?)
    # ?? ???? update ??
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true    # ??? SQL ??? ??
        show_sql: true      # ???? SQL ???
  # ? [??] ?? ??? ?? ?? ?? (?? 1MB -> 20MB)
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
# ?? ?? ?? (?? 8080)
server:
  port: 8080